title: Projet MakerSpace
description: Voici la présentation de la conception et construction de notre projet “Machines That Draws”
theme: just-the-docs

url: https://Avsin6z.github.io
baseurl: /projet-makerspace
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
